- name: backend configuration
  hosts: backend
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y

  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.command: dnf install nodejs -y

  - name: create expense user
    ansible.builtin.user:
      name: expense

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory  #here we should give 'state: directory' otherwise it creates 'file' by default.

  - name: downloading backend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: extracting backend code
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app